### ISSUE TITLE
大侠 更新后 直接奔溃！！！

### ISSUE THREAD

**Issue by heliang219** [rztime/RZColorful#11]
奔溃信息：
Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray objectAtIndex:effectiveRange:: Out of bounds'

**Comment by rztime** [comment]
这看来是数据越界，请定位看看数据crash在我这边代码哪个位置？

**Comment by heliang219** [comment]
<img width="1147" alt="截屏2023-02-02 15 19 34" src="https://user-images.githubusercontent.com/795426/216257694-f486ee6c-24a7-477c-9c0a-a2117ba579f2.png">

**Comment by rztime** [comment]
抱歉，忽略了空字符串，已修改，请更新一下
