### ISSUE TITLE
confer.paragraphStyle.alignment(NSTextAlignmentRight); // 可以设置文本显示在左、中、右 （在foldType = RZFoldLabelFoldTypeNextRow 时才生效)

### ISSUE THREAD

**Issue by wenhao-fly** [rztime/RZColorful#13]
这个RZFoldLabelFoldTypeNextRow没找到在哪里设置啊, 这个收起怎么放到最右边去，而不是放在文字后面

**Comment by rztime** [comment]
这个可能是你们自己加的。
如果要放到最右边，建议做法：
1. 创建NSAttributedString，placeholder就是你要显示”全文“的占位文字，这个文字设置透明（第3步，"全文"按钮会遮挡）
`- (NSAttributedString * _Nullable)rz_attributedStringBy:(NSInteger)maxLine maxWidth:(CGFloat)width lineBreakMode:(NSLineBreakMode)model placeHolder:(NSAttributedString *_Nullable)placeHolder;`
2.第一步的NSAttributedString的string和你的原本文字text做比较，如果一致，则表示能完全显示
3.在右下角加一个”全文“按钮，如果2中不能完全显示，则将此按钮显示出来
